server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/greenhotel?useSSL=false&allowPublicKeyRetrieval=true
    username: hr
    password: 1234
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: hsy010517@naver.com #네이버 아이디
    password: "@tjduddl010517" #네이버 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  #      hibernate.globally_guoted_identifiers: true

  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234